ubaseURL: "https://whitematter.tech"
title: WhiteMatterTech
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
googleAnalytics: "UA-193676598-1"

minify:
    disableXML: true
    # minifyOutput: true
#
#
languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Posts
                  url: posts
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Categories
                  url: categories/
                  weight: 10
                - name: W3RDW
                  url: https://w3rdw.radio
                  weight: 10

markup:
  goldmark:
    renderer:
      unsafe: true

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
#    profileMode:
#      enabled: true
#      title: "Robert D. White" # optional default will be site title
#      subtitle: "Enterprise Services Engineer @ Tanium // Consultant"
#      imageUrl: "profile/rdw.jpg" # optional
#      imageWidth: 120 # custom size
#      imageHeight: 120 # custom size
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    #description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    author: Robert D. White
    # author: ["Me", "You"] # multiple authors
    defaultTheme: dark
    disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    disableSpecial1stPost: false
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    comments: false
    images: ["brain.jpg"]
    logo:
      logoHomeLink: "/"
      logoMark: ">#"
      logoText: "./whitematter.tech"
      logoCursorDisabled: false
      logoCursorAnimate: "2s"
      logoCursorColor: "#67a2c9"
    homeInfoParams:
        Title: "Robert D. White"
        Content: >
            IT & Cybersecurity Professional // Consultant
        imageUrl: "profile/rdw.png"

    socialIcons:
        - name: github
          url: "https://github.white.fm"
        - name: linkedin
          url: "https://linkedin.white.fm"
        - name: twitter
          url: "https://twitter.white.fm"
 #       - name: mastodon
 #         url: "https://robertwhite.social"
        - name: googlescholar
          url: "https://scholar.white.fm"
        - name: matrix
          url: "https://matrix.to/#/#whitematter:white.fm"
        - name: telegram
          url: "https://t.me/+xaDqeY0b0CRjZWUx"
        - name: email
          url: "mailto:robert@whitematter.tech"
        - name: RsS
          url: "index.xml"

    editPost:
        URL: "https:///github.com/RobertDWhite/WhiteMatterTech/edit/main/content"
        Text: "Suggest Changes @ GitHub" # edit text
        appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35
    #
    analytics:
        google:
           SiteVerificationTag: "gtag('config', 'UA-193676598-1')"

assets:
    favicon: "/favicon.ico"
    favicon16x16:  "/favicon-16x16.png"
    favicon32x32:  "/favicon-32x32.png"
    apple_touch_icon:  "/apple-touch-icon.png"
    safari_pinned_tab:  "/safari-pinned-tab.svg"
    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]



taxonomies:
    category: categories
    tag: tags
    series: series

    twitter:
        disabled: false
        enableDNT: true
        simple: true
