baseurl      = "https://whitematter.tech"
title        = "WhiteMatter Technology"
languageCode = "en-us"
theme        = "hello-friend-ng"
paginate     = 10
rssLimit  = 20  # Maximum number of items in the RSS feed.
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License." # This message is only used by the RSS template.
enableGitInfo   = true
enableEmoji     = true
enableMissingTranslationPlaceholders = false
disableRSS     = false
disableSitemap = false
disable404     = false
disableHugoGeneratorInject = false

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"

  GithubEdit = "https:///github.com/RobertDWhite/WhiteMatterTech/edit/main/"
  # Subtitle for home
  homeSubtitle = "Enterprise Services Engineer // Consultant"

  # Set disableReadOtherPosts to true in order to hide the links to other posts.
  disableReadOtherPosts = false

  # Enable sharing buttons, if you like
  enableSharingButtons = true

  # Metadata mostly used in document's head
  description = "WhiteMatterTech blog and resume"
  keywords = "homepage, blog"
  images = [""]

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
  [languages.en]
    title = "Robert D. White"
    subtitle = "Enterprise Services Engineer // Consultant"
    keywords = ""
    copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "sudo ./whitematter.tech"
      logoHomeLink = "/"
    # or
    #
    # path = "/img/your-example-logo.svg"
    # alt = "Your example logo alt text"

  # And you can even create generic menu
  [[menu.main]]
    identifier = "posts"
    name       = "Posts"
    url        = "/posts"

  [[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact"

  [[params.social]]
    name = "linkedin"
    url = "https://linkedin.white.fm"

  [[params.social]]
    name = "twitter"
    url = "https://twitter.white.fm"

  [[params.social]]
    name = "github"
    url = "https://github.white.fm"

  [[params.social]]
    name = "googlescholar"
    url = "https://scholar.google.com/citations?hl=en&authuser=1&user=uZOlQSsAAAAJ"

  [[params.social]]
    name = "email"
    url = "mailto:robert@whitematter.tech"
