baseURL: "https://whitematter.tech"
title: WhiteMatterTech
paginate: 5
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true
# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Posts
                  url: posts
                  weight: 5
                - name: Search
                  url: search/
                  weight: 10
                - name: Tags
                  url: tags/
                  weight: 10
                - name: Categories
                  url: categories/
                  weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    #description: "Theme PaperMod - https://github.com/adityatelange/hugo-PaperMod"
    author: Robert D. White
    # author: ["Me", "You"] # multiple authors
    defaultTheme: auto
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowCodeCopyButtons: true
    ShowToc: true
    # comments: false
    images: ["brain.jpg"]
    logo:
      logoHomeLink: "/"
      logoMark: ">"
      logoText: "$ sudo ./whitematter.tech"
      logoCursorDisabled: false
      logoCursorAnimate: "2s"
      logoCursorColor: "#67a2c9"
    homeInfoParams:
        Title: "Robert D. White"
        Content: >
            Enterprise Services Engineer @ Tanium // Consultant
        imageUrl: "profile/rdw.jpg"

    socialIcons:
        - name: github
          url: "https://github.white.fm"
        - name: linkedin
          url: "https://linkedin.white.fm"
        - name: twitter
          url: "https://twitter.white.fm"
        - name: googlescholar
          url: "https://scholar.white.fm"
        - name: email
          url: "mailto:robert@whitematter.tech"
        - name: RsS
          url: "index.xml"

    editPost:
        URL: "https:///github.com/RobertDWhite/WhiteMatterTech/edit/main/content/"
        Text: "Suggest Changes @ GitHub" # edit text
        appendFilePath: true # to append file path to Edit link

    # label:
    #     text: "Home"
    #     icon: icon.png
    #     iconHeight: 35

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    # assets:
    #     favicon: "<link / abs url>"
    #     favicon16x16: "<link / abs url>"
    #     favicon32x32: "<link / abs url>"
    #     apple_touch_icon: "<link / abs url>"
    #     safari_pinned_tab: "<link / abs url>"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]



taxonomies:
    category: categories
    tag: tags
    series: series

    twitter:
        disabled: false
        enableDNT: true
        simple: true
